### ISSUE TITLE
Email addresses should be validated before allowing alerts to be sent

### ISSUE THREAD

**Issue by OmgImAlexis** [thinkst/canarytokens#101]
Currently there's no verification before alerts are sent out meaning I can just add people's emails and have this send them unsolicited emails.

From what I could see there's also no way to opt out of these via the email.

**Comment by NDevTK** [comment]
Emails contain canarytokens.org/manage that has a emails alert toggle so people can "unsubscribe"
In order to verify a email address without something like Google OAuth it would also have to send a unsolicited email.
However fake tokens could be used to troll people who dont know there token IDs.

**Comment by jayjb** [comment]
Hi @OmgImAlexis and @OmgImAlexis,

Correct. And we have seen it happen here and there. We encourage folks to email us if they are getting "trolled" or spammed from our site and dont know about the Canarytoken. We can then simply remove it.

Our thinking with the verification is that it is another barrier. We haven't seen enough abuse of the site to warrant adding such safe guards (yet)

**Comment by OmgImAlexis** [comment]
@jayjb you tagged me twice.

> We encourage folks to email us if they are getting "trolled" or spammed from our site and dont know about the Canarytoken. We can then simply remove it.

Why not include a link directly in the email?

**Comment by NDevTK** [comment]
@OmgImAlexis theirs a manage link in the email
