### ISSUE TITLE
Payload domain

### ISSUE THREAD

**Issue by jtagcat** [thinkst/canarytokens#112]
Have a separate token domain(s) from the dashboard domain.

If it was smartcoconut.com instead of canarytokens.org, it'd be less obvious.

You don't have to be familiar with canarytokens.org, the format, etc. 'canary' would make me snap out, with 'hold on', maybe visit the root domain first.

smartcoconut.com should be blank (no generate dashboard).

**Comment by jayjb** [comment]
Hi @jtagcat,

Thanks for the suggestion. Canarytokens.org serves as a demo for folks. We encourage folks to rather create their own Canarytokens server using our docker setup. This way you can make the domains as obscure as you like.
