### ISSUE TITLE
Grafana or elasticsearch integrations? 

### ISSUE THREAD

**Issue by mrrobotnl** [thinkst/canarytokens#114]
I am currently working on a project for school. Is it perhaps possible to connect a canary token to a monitoring software like Grafana? So that I can display when en who has opened a pdf or word file?

**Comment by jayjb** [comment]
Hi @mrrobotnl,

You could provide the webhook address of your elasticsearch or Grafana instance and allow the Canarytokens.org server to post alerts to those instances (if they allow alert ingestion via webhooks). 

Alternatively, you could create an AWS lambda that receives the webhook POST from Canarytokens.org; takes that data and constructs it into a form that ElasticSearch or Grafana can use, and then POST it to those instances

**Comment by jayjb** [comment]
Closing this issue because we don't plan on supporting those integrations at the moment. Please reopen if you would like to discuss this more.
