### ISSUE TITLE
Don't put the DNS nameserver as a subdomain of the canary token

### ISSUE THREAD

**Issue by bawolff** [thinkst/canarytokens#121]
While using this token to test log4j, I encountered a system that appears (this is based on some guess work) to look up the A record of the DNS nameserver for the canary token. Some of this is based on guess work, but it looks like the DNS resolver first did a NS lookup on L4J.y5iy21lmuu8oilvgcovzx1xd5.canarytokens.com. saw it was ns1.L4J.y5iy21lmuu8oilvgcovzx1xd5.canarytokens.com. so then decided to do an A record look up on that domain

This resulted in a false positive result where  the canary token reported a hit with a log4shell hostname of s1 (Since the first letter is stripped). This was very confusing.

I'd suggest putting the nameserver  domain somewhere else so that lookups of it don't trigger the token, or perhaps making the log4j hostname detection require the subdomain to start with x, so if the subdomain is ns1, it doesn't report a hostname of s1.

**Comment by jayjb** [comment]
Hi @bawolff,

Thanks so much for reporting this. Im looking at the structure of the log4j token and its recommended usage:
```
${jndi:ldap://x${hostName}.L4J.TOKEN_STRING.canarytokens.com/a}
```
And I am seeing an `x` there but when looking at the regex used `re.compile('([A-Za-z0-9.-]*)\.L4J\.', re.IGNORECASE)` which doesn't check for the `x`. 

Fix is on the way. We will check for the preceding `x`, however we will still alert if no hostname found. This is a precaution, but we wont show a false host.

**Comment by jayjb** [comment]
Hi @bawolff,

There is a fix in for this already. It will be rolled out with the new version of canarytokens shortly. Thank you for reporting this! If you wouldn't mind emailing me at jay [at] thinkst [dot] com. We would like to send you something.
