### ISSUE TITLE
Infinite loop in redirect if http not specified

### ISSUE THREAD

**Issue by 3ICE** [thinkst/canarytokens#122]
I entered my website only as "3ice.hu" into the slow redirect's URL field as a test, and it caused an infinitely looping self-redirect canary... Please prepend "http://" if your users forget. Or redirect properly so web browsers don't have to guess.

Expected: canarytokens.com -> http://3ice.hu/
Actual: canarytokens.com -> canarytokens.com -> canarytokens.com :|| ... ad infinitum

_blog.thinkst / canarytokens org: "Your comment will be visible after approval."
???
Okay, when? 7 days..._

**Comment by 3ICE** [comment]
http://canarytokens.com/about/kuzfh7vtq26ox5ye8h7h9bcl2/post.jsp
ˇˇ
http://canarytokens.com/about/kuzfh7vtq26ox5ye8h7h9bcl2/3ice.hu
ˇˇ
http://canarytokens.com/about/kuzfh7vtq26ox5ye8h7h9bcl2/3ice.hu
ˇˇ
> This page isn’t working
> canarytokens.com redirected you too many times.
> Try clearing your cookies.
> ERR_TOO_MANY_REDIRECTS

Oh, and no e-mail.

**Comment by wleightond** [comment]
Hi @3ICE,

Thank you for raising this! GitHub issues/discussions are the right place to raise these issues.

It has been fixed in #259 which is now live on [canarytokens.org](https://canarytokens.org/). Please let us know if anything is still broken for you!
