### ISSUE TITLE
webhook resend on failure?

### ISSUE THREAD

**Issue by JiTmun** [thinkst/canarytokens#123]
Hello,
Using hooks, if the hook endpoint is down for any reason, will a canarytoken try to reach the hook  endpoint forever, so that when the hook endpoint is back the hook is triggered?

**Comment by jayjb** [comment]
Hi @JiTmun,

No. The reason for this is because if a webhook endpoint is down indefinitely, we don't want to waste time on retrying indefinitely.

**Comment by jayjb** [comment]
Closing this issue for now. Please reopen if you have more to discuss.
