### ISSUE TITLE
HOWTO for generating templates?

### ISSUE THREAD

**Issue by hillu** [thinkst/canarytokens#13]
I wanted to do my own canary documents and tinkered around a bit with the `template.docx` provided in this repository. This are the steps I came up with:

1. Somewhere in the document, insert an image, for example a one-pixel
   GIF file called `1x1.gif`, and set its size to 0x0, save the file.
2. In the ZIP structure, open `word/document.xml` find
   `name="1x1.gif"` the reference ID, for example `<a:blip
   r:embed="rId5"/>`.
3. Edit `word/_rels/document.xml.rels`, find the matching `Relationship`
   tag, for example:
   ```
   <Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image1.gif"/>
   ```
   Replace the `Target` value `media/image1.gif` with the
   string `HONEYDROP_TOKEN_URL`, add `TargetMode="External"`.
4. Remove `media/image1.gif`.

The result is different from your `template.docx`. Apart from the fact that there are not `header*.xml` or `footer*.xml` files since I added the image into the main document, the image constuct looks entirely different. Instead of the `<w:instrText>` tag including the `INCLUDEIMAGE` instruction, I simply get a `<w:drawing>` tag in which the GIF is referenced. Cursory testing shows that (at least) Word 2010 will also try to load the file, so the needed functionality seems to be there. However, since I am by no means an Office expert, I wonder what I am missing.

Could you please document how you generated the templates and why specific steps were taken?

**Comment by thinkst** [comment]
Hi @hillu,

We currently have multiple techniques for “tagging” office docs. 
As you noticed, each technique has two challenges to overcome 
1) the beacon;
2) automatically inserting this beacon into the document.

We played with various techniques for (2) including headless machines and document automation.
Your technique sounds perfectly reasonable. Checkout msword.py to see how we did it (we place the image in the footer).
