### ISSUE TITLE
Firewall config - which port needed to be open ? 

### ISSUE THREAD

**Issue by GitWatin** [thinkst/canarytokens#136]
Hi, 
It's not a bug request, just info.

Can you tell me which port need to be open to allow canarytoken traffic ? 
Did you use IP or DNS name to contact your server ? 

Thanks you in advance for your answer 

Regards

**Comment by ranok** [comment]
You will at least need 80 and 53 open (UDP and TCP) for the web bugs and the DNS tokens. If you're running the HTTPS version you'll need 443 as well.

**Comment by jayjb** [comment]
Closing this issue as resolved. Thanks @ranok! 🤘 Please re-open if there is more to discuss
