### ISSUE TITLE
Quick Question - URL simple view 

### ISSUE THREAD

**Issue by markthompson1** [thinkst/canarytokens#153]
Hi,

I have reinstalled a personal Canary Token server. However, the first time I did this, I was able to simplify the Canary Token to just show the token in the URL vs trying to disguise or obfuscate the fact that it was a canary token. 

Simple View - http://example.com/o1e15p712l27t1b5jjtqfs6jo

vs

Obfuscated View - http://example.com/images/o1e15p712l27t1b5jjtqfs6jo/submit.aspx

I'd like to change to a simple view again but I can't remember where the option to do this is configured, and I'm struggling to find it the second time around.

Does anyone have this information to hand or could point me to where this information is?

Thanks, 

Mark

**Comment by jayjb** [comment]
Hi @markthompson1,

If i recall correctly, we don't have a setting that controls that (not to my knowledge). Looking at the code though, if you check in setup_db.py, you will notice a method `add_canary_path_element` which adds the path elements that are randomised. You could either remove the path elements there, or alternatively, remove the `'canary_path_elements'` key from your redis database which is where the path elements are stored.

**Comment by jayjb** [comment]
Closing this issue as inactive. Please reopen it if you want to have more of a discussion.
