### ISSUE TITLE
No email notification......

### ISSUE THREAD

**Issue by demproper** [thinkst/canarytokens#154]
I have created two tokens, a windows directory and a word document. Both are placed on the desktop, I receive no email notification after the tokeks are opened.  Running 64 Bit Win 10 21H1, token created at  "canarytoken.org".

Thank you in advance.....

Daryl

**Comment by jayjb** [comment]
Hi @demproper,

Thanks for reporting this. We will take a look into it.

Can you please confirm the following:
1. What program did you use to open the Word document?
2. Did you mark the document as safe after downloading it? With Windows if you download something, it is marked as "from the internet" and won't trigger.

**Comment by jayjb** [comment]
Closing this issue as we haven't got a response with more information. Please re-open if you still have the issue
