### ISSUE TITLE
GCP user tokens?

### ISSUE THREAD

**Issue by neilstuartcraig** [thinkst/canarytokens#16]
Hi

I've been tinkering a little with Canary Tokens and I like it a lot - loads of value for very little effort. I'm working on a project which will be deployed on AWS and Google Cloud (GCP) so i'd be really interested to know if you are planning on providing a GCP equivalent to the AWS user auth tokens facility which is already in CT? I haven't thought it through much but i assume/hope it's feasible.

Cheers

**Comment by OmarDarwish** [comment]
Hey there, have there been any updates regarding GCP tokens?

Also, could you please point to where AWS tokens are monitored?

**Comment by thinkst** [comment]
Hey @OmarDarwish,

The GCP tokens are still being looked into at the moment; wrt the AWS tokens, we wrote a blog post on how we went about doing it over [here](http://blog.thinkst.com/2017/09/canarytokens-new-member-aws-api-key.html)

**Comment by thinkst** [comment]
Closing this issue. Will notify everyone when GCP User tokens are available.

**Comment by dirsigler** [comment]
Is there any update after 4 years?
There are probably multiple companies and people of all sizes which would be interested.

I am also interested in GCP canary tokens for a 500 manpower big company.
