### ISSUE TITLE
DNS token reports have a weird private network Source IP

### ISSUE THREAD

**Issue by differentblue** [thinkst/canarytokens#175]
I have created a new test DNS token.  After triggering, the email report consistently has
Source IP: 192.168.64.1
even when triggering it from two widely separate systems.
That private network block is not visible on traceroute between me and the internet

The source IP used to be generally indicative in the past.   Something has changed?

![image](https://user-images.githubusercontent.com/32970961/213456385-0d2432e4-2e71-4d51-b242-d4ec2a75be1f.png)

**Comment by jayjb** [comment]
Hi @differentblue,

Thanks so much for reporting it. We have since fixed it. Please would you mind emailing me at `jay [at] thinkst [dot] com`. We have something for you for reporting it!

**Comment by differentblue** [comment]
Seems to be working properly.  Thanks for you help!
