### ISSUE TITLE
URL Token notifications from Google

### ISSUE THREAD

**Issue by seranu** [thinkst/canarytokens#18]
Hi,
I set up an URL canary token and saved it somewhere on my machine. I got two notifications last night that seem to be coming from Google. 
Is this possible that Google would crawl the canary token page? Or maybe something else?

Regards,
seranu

**Comment by thinkst** [comment]
Hi Seranu.

The most likely candidate here, is if you have some sort of tool bar additions or extensions. (We don’t expose the token to google for indexing).

Are you running any sort of browser extensions?

/mh 

__
Haroon Meer
+27 83 786 6637
http://thinkst.com/pgp/haroon.txt

**Comment by seranu** [comment]
Update: I just remebered that I have shortened the URL using google URL shortener. Interesting stuff. Does this mean that everytime someone accesses the token, alerts will come from Google?

**Comment by thinkst** [comment]
Hey Seranu,

Which token type did you create? With the DNS token you will only ever see which DNS servers (not local IP), triggered the token.

If it was a Web token, I suspect that Google may do some trickery around making sure the URL its shortening is not something malicious. To check this, it would probably try GET the url and check the contents. This would trigger an alert. 

Please let me know if there is anything else (or if you would like to discuss this further)

**Comment by thinkst** [comment]
Closing this issue because of no reply and it is an old thread. Please reopen if you want to revisit this issue.
