### ISSUE TITLE
canarytokens.com Categorized URL - Malicious Site

### ISSUE THREAD

**Issue by wilmerism** [thinkst/canarytokens#182]
Im fault finding some tokens.
A router was blocking the outbound because the site is categorized as >

Categorization in URL Filter database version '499745'
URL Status Categorization Reputation
http://canarytokens.com/	Categorized URL - Malicious Sites

    PUPs (potentially unwanted programs)
    High Risk

on https://sitelookup.mcafee.com/en/feedback/url - Ive submitted to get it re-categorized as business

Then just looking on another i get "botnet" > https://www.cyren.com/security-center/url-category-check-gate

**Comment by jayjb** [comment]
Hi @wilmerism,

I checked on the mcafee site now and noticed that it is categorised as business with a low risk. Thanks for reporting this though; we can try keep an eye on it.
