### ISSUE TITLE
SMTP Output Channel?

### ISSUE THREAD

**Issue by obsti8383** [thinkst/canarytokens#21]
Hey @thinkst : 

Would you accept a Pull Request that implements SMTP (over TLS) as an output channel?

I would like to have that for my installation so that I must not depend on third party mailproviders (but use my own SMTP server).

**Comment by ndom91** [comment]
@obsti8383 have you implemented this in your setup?

Im trying to be able to use my own smtp server instead of the provided mailgun / sendmail configs.

If you'd be willing to share, I'd be very thankful :smiley:

**Comment by thinkst** [comment]
Hey @obsti8383,

That would be totally awesome! (and we may be able to send you some swag for contributing, I know a person ;) )

**Comment by obsti8383** [comment]
I'll take a look.

**Comment by ndom91** [comment]
@obsti8383 you are the man(woman)! I'll take a look at this as soon as I have some free time in the next day or two. Thanks!!

**Comment by thinkst** [comment]
Hey @obsti8383,

Thanks so much for the PR (and the great work inside it). I am currently reviewing it and testing it to make sure. Ill hit you back shortly with some meaningful comments. 

In the meanwhile, would you mind dm'ing me your details so we can send some swag over to say thanks.

**Comment by obsti8383** [comment]
> Hey @obsti8383,
> 
> Thanks so much for the PR (and the great work inside it). I am currently reviewing it and testing it to make sure. Ill hit you back shortly with some meaningful comments.
> 
> In the meanwhile, would you mind dm'ing me your details so we can send some swag over to say thanks.

Hi @thinkst: Thanks, just come back to me if you find any issues. Under which E-Mail address can I reach you?
