### ISSUE TITLE
Sensitive Command Token Doesn't Work with All Executables

### ISSUE THREAD

**Issue by sadikassistivlabs** [thinkst/canarytokens#212]
For example it doesn't seem to work with an installed `nmap`. 

But it works fine with any executables from '`C:\Windows\System32\` including `whoami` and `ipconfig`

I'm wondering if the executable has to end itself in a particular way in order for the tripwire to work. Per https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/registry-entries-for-silent-process-exit it says

"
In the context of this monitoring feature, we use the term silent exit to mean that the monitored process terminates in one of the following ways.

Self termination
The monitored process terminates itself by calling ExitProcess.

Cross-process termination
A second process terminates the monitored process by calling TerminateProcess.

The monitoring feature **does not detect normal process termination that happens when the last thread of the process exits**. The monitoring feature does not detect process termination that is initiated by kernel-mode code.
"

which seems to imply that if the executable doesn't explicitly call ExitProcess to terminate itself, a silent exit won't be triggered.

If this is expected behavior, it might be nice to have this called out in the docs somewhere. It took quite a while for me to even get to this hypothesis

**Comment by jayjb** [comment]
Hi @sadikassistivlabs,

Thanks so much for reporting this. We think we have found the issue and are trying out some fixes for it. The just of it is that 32bit and 64bit executables seem to be behaving differently. 

Ill have more information for you soon.

**Comment by azh-r** [comment]
Thanks for all the digging @sadikassistivlabs. The key difference here is that registry keys need to be installed for both 32 and 64 bit executables. The solution is to import the Canarytoken .reg file, with both a 32 and 64 bit view of registry ie. by running the below instead of the single import command:

```
reg import FILENAME /reg:64
reg import FILENAME /reg:32
```

We'll update the installation docs for this.
