### ISSUE TITLE
Simple Typo Fix on Template

### ISSUE THREAD

**Issue by thinkst-cs** [thinkst/canarytokens#214]
This page reads:

https://github.com/thinkst/canarytokens/blob/d497e9d33522dd227d62b26abbfb829016e2d691/templates/generate_new.html#L627

```
Since DNS is used as the underlying transport, the Source IP will be that of a DNS server, not the databserver
```

Should Read:

`databserver s/b "database server"`

**Comment by thinkst-marco** [comment]
Fixed in #215.
