### ISSUE TITLE
Thwarting Malware

### ISSUE THREAD

**Issue by Technetium1** [thinkst/canarytokens#221]
Someone is distributing malware through Discord. They're using Canarytokens to log victims. I want to either destroy the usefulness of their logs, or get the endpoint removed. How can I accomplish this?

If anyone wants to look at the malware you can find it by searching `rolaslegacy`

`http://canarytokens.com/0grfo6bh0wcepfnk01gmkw45n.jpg`

**Comment by jayjb** [comment]
We cleaned up the relevant token
