### ISSUE TITLE
Credit Card token (beta) not working

### ISSUE THREAD

**Issue by tiagorangel2011** [thinkst/canarytokens#224]
I am unable to create a Credit Card token.
Error: Credit Card Rate-Limiting currently in place. Please try again later.
I have never created one, and I have waited and tried again. Same error.
I'm using the canary tokens website.

**Comment by benjamin-thinkst** [comment]
Hi @tiagorangel2011,
We a monthly limit of a few hundred/1000 per month. Sorry you hit this limit you'll have to try again early next month. 
Thanks for using canarytokens!

**Comment by tiagorangel2011** [comment]
Hello. The limit was **not** hit, as this was the _first_ time I used the feature.

**Comment by wleightond** [comment]
Hi @tiagorangel2011,

Just jumping in to clarify, our credit card provider limits us to hundreds of tokens per day globally, so the limit is on our side. I'll leave the issue closed for now, but feel free to ask if you have any further questions.
