### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by wifiuk** [thinkst/canarytokens#24]
Can you update this repo with installation and usage instructions

**Comment by thinkst** [comment]
Hey @wifiuk,

Which part of the setup specifically are you battling with? (in which case I know I should elaborate more in this section.)

Thanks for taking an interest in our Canarytokens.

**Comment by thinkst** [comment]
Hey @Zeik0s,

In terms of explanation of each file, would it be better if that was included in each file (like at the top of the `.py`) or a separate wiki section that explains certain concepts that are in the canarytokens project? We know our documentation isn't great (yet!), so we planning on making it better.

**Comment by Zeik0s** [comment]
@thinkst in a separate Wiki would be better i think. :relaxed:

**Comment by jayjb** [comment]
Hey @wifiuk, @Zeik0s,

We haven't created a wiki (yet), but we have updated the `README.md` on [canarytokens-docker](https://github.com/thinkst/canarytokens-docker). Take a look and let me know if they help. I have added that we should create wiki.

**Comment by Zeik0s** [comment]
ok, will have a look. Thanks!
