### ISSUE TITLE
mail

### ISSUE THREAD

**Issue by jujumanman** [thinkst/canarytokens#293]
The mail alert  dosen't work all the time. So how can i know if it's my mailset's fault?

**Comment by benjamin-thinkst** [comment]
@jujumanman Thanks for reporting the issue.
I'm missing some context: Are you running your own instance of `canarytokens` or using [canarytokens.org](https://canarytokens.org/generate)?

If you running your own instance:
1. Which mail provider are you using (mailgun or sendgrid or smtp)?
2. you can check the logs using `[docker log](https://docs.docker.com/engine/reference/commandline/logs/)`

If you using  [canarytokens.org](https://canarytokens.org/generate):
1. It's likely that you hit a rate limit `MAX_ALERTS_PER_MINUTE ` which is 1. Does this explain what you have seen ("mail alert dosen't work all the time") ?


Super happy to investigate further if the above doesn't explain what you are seeing 😀.
