### ISSUE TITLE
Discord Webhook Support

### ISSUE THREAD

**Issue by chrisreeves-** [thinkst/canarytokens#314]
**Describe the bug**
At the page https://canarytokens.org/generate# trying to create a Canary with a Discord webhook returns "Invalid webhook supplied, confirm you can POST to this URL with:"

**To Reproduce**
1. Go to https://canarytokens.org/generate#
2. Select a canary type
3. Enter the Discord webhook URL
4. Enter text
5. Click "Create my Canarytoken"

**Expected behavior**
Canary should be created from the test it preforms.

**Screenshots**
![image](https://github.com/thinkst/canarytokens/assets/9957942/df896a08-ffc5-43de-a135-a288838c1715)

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser: Chrome

**Additional context**
Tested using curl appending the "/slack" to the end of the URL works
![image](https://github.com/thinkst/canarytokens/assets/9957942/ae9dcdee-ad5a-4da0-9a0f-7a46be476731)
This unfortunantley doesn't work in the webpage with the /slack appended.

**Comment by quinn-thinkst** [comment]
Hi @chrisreeves-

Thanks for raising this. This is an unfortunate side effect of Discord taking an unusual webhook format, and as a result not working with the standard output (though it's certainly interesting that the "/slack" inclusion actually makes it behave, I wouldn't have expected that).

We've had internal chatter in the past about adapting the webhook functionality to support Discord, but until now that hasn't come to anything. I'll raise this again and we'll get this working ASAP - so thanks again for the nudge!

**Comment by chrisreeves-** [comment]
Hey @quinn-thinkst thanks for the reply.

I found a way to do it by transforming the JSON payload being sent by using webhookrelay.com
They use lua for the transform, I'll leave the snippet I used to get it going _(for others interested in this solution)_

```
local json = require("json")

local body, err = json.decode(r.RequestBody)
if err then error(err) end

local token_type = body["token_type"]
local src_ip = body["src_ip"]
local time = body["time"]
local memo = body["memo"]

local message = "Canary triggered @ " .. body["time"] .. " src_ip: " .. body["src_ip"] .. " Source: " .. body["memo"] .. " Manage URL: " .. body["manage_url"]

-- Preparing Discord payload
local discord = {
    username= "OpenCanary",
    content= message
    }

local result, err = json.encode(discord)

-- Set modified request body
r:SetRequestBody(result)
``` 

![Screenshot 2023-10-31 at 2 39 02 pm](https://github.com/thinkst/canarytokens/assets/9957942/3f7b1196-4e03-4ac3-833d-1b3c48ddcf3a)

**Comment by quinn-thinkst** [comment]
Hey @chrisreeves- 

I'm sorry this has taken a little while to get sorted (that's on me). Official support for discord webhooks is up and running now, so you can setup your tokens directly hooked into discord rather than needing an intermediary (but nice find on the relay - that's a nifty hack that should be usable for any case of an unsupported webhook).

Thanks again for raising this issue, and please do shout if you bump into any issues with the feature!
