### ISSUE TITLE
[BUG] "An error has occurred: Internal Server Error" message when trying to create a credit card token

### ISSUE THREAD

**Issue by BjoernKW** [thinkst/canarytokens#317]
**Describe the bug**
A "An error has occurred: Internal Server Error" message is displayed when trying to create a credit card token under https://canarytokens.org/generate

**To Reproduce**
1. Go to https://canarytokens.org/generate
2. Select 'Credit Card token (beta)'
3. Enter a valid email address and a note.
4. See error.

**Expected behavior**
A token should be generated

**Screenshots**
<img width="637" alt="Screenshot 2023-10-24 at 12 47 38" src="https://github.com/thinkst/canarytokens/assets/125270/1c4a7d94-6951-446a-a665-1d768651ccc9">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: 1.59.122 Chromium: 118.0.5993.96 (Official Build) (arm64)

**Comment by KUKHUA** [comment]
Is this intended or something?
It does not work, tested on 3 browsers.

**Comment by KUKHUA** [comment]
Is this related to #224?

**Comment by ranok** [comment]
Yes, it is the limitations of the issuer, so if we don't have any more available to issue it provides that error.

We are working on integration with a new provider that should offer higher limits.
