### ISSUE TITLE
[BUG] error webhook sent with wrong content-type

### ISSUE THREAD

**Issue by colin-stubbs** [thinkst/canarytokens#322]
**Describe the bug**

Error webhooks are sent as `Content-Type: application/x-www-form-urlencoded` when the payload is actually JSON.

The Content-Type header should be set to `application/json` when POST'ing the webhook.

e.g. this from https://github.com/thinkst/canarytokens/blob/master/canarytokens/loghandlers.py,

```
def httpRequest(postdata):  # pragma: no cover
    agent = Agent(reactor)
    headers = {b"Content-Type": [b"application/x-www-form-urlencoded"]}
    data_str = json.dumps(postdata)
    body = BytesProducer(data_str.encode())
    url = os.getenv("ERROR_LOG_WEBHOOK").encode()
    d = agent.request(b"POST", url, Headers(headers), body)

    def handle_response(response):
        if response.code == 200:
            d = defer.succeed("")
        else:
            log.warn("Failed to post to webhook")
            d = None
        return d

    d.addCallback(handle_response)
    return d
```

should be,

```
def httpRequest(postdata):  # pragma: no cover
    agent = Agent(reactor)
    headers = {b"Content-Type": [b"application/json"]}
    data_str = json.dumps(postdata)
    body = BytesProducer(data_str.encode())
    url = os.getenv("ERROR_LOG_WEBHOOK").encode()
    d = agent.request(b"POST", url, Headers(headers), body)

    def handle_response(response):
        if response.code == 200:
            d = defer.succeed("")
        else:
            log.warn("Failed to post to webhook")
            d = None
        return d

    d.addCallback(handle_response)
    return d
```

**To Reproduce**

1. Configure the error webhook URL via `ERROR_LOG_WEBHOOK` to go to any system which tries to utilise Content-Type to understand what it has received and parse it correctly.
2. Fail.

**Expected behavior**

I expect the code to correctly set the Content-Type header to match the content type that is being sent, so that receiving systems can understand what is being sent to them.

**Screenshots**

None, refer to above.

**Desktop (please complete the following information):**

Not applicable.

 **Smartphone (please complete the following information):**

Not applicable.

**Additional context**

Not applicable.

**Comment by thinkst-pieter** [comment]
@colin-stubbs, thanks for reporting this. The fix is now live on canarytokens.org.
