### ISSUE TITLE
Enable wildcard CORS support

### ISSUE THREAD

**Issue by i-am-shodan** [thinkst/canarytokens#329]
**Is your feature request related to a problem? Please describe.**
I'm trying to deploy a custom image web bug with the css mentioned here.
https://zolder.io/using-honeytokens-to-detect-aitm-phishing-attacks-on-your-microsoft-365-tenant/

It doesn't work i'm getting this error in the browser (i'm using the latest docker build)
![image](https://github.com/thinkst/canarytokens/assets/6901273/7097b39e-10c0-4d7f-90c2-2f6ea236dc10)

**Describe the solution you'd like**
I think a new CORS policy is needed. I've added /img.png to the web bug but I can't get the CORS policy to be correct for the linked scenario.

**Describe alternatives you've considered**

**Additional context**

**Comment by i-am-shodan** [comment]
I think what's happening in this case is that the CORS preflight check isn't returning a success code

**Comment by jayjb** [comment]
Hi @i-am-shodan,

Thanks for reporting in. This is an interesting use case. Am i correct in assuming that you are trying to use 
```
.ext-footer
{
    background-image: url('<LINK>');
    background-size: 0 0;
}
```
where you replace the `<LINK>` with a web image bug?

**Comment by i-am-shodan** [comment]
Yep thats it. Looking a the browser it fails the CORS preflight check.

**Comment by i-am-shodan** [comment]
Worth saying I can also get this use case to work if I host the image on a service I control and correctly set a wildcard CORS policy.

**Comment by jayjb** [comment]
Hi @i-am-shodan,

Would you minding trying this using a "custom web image bug"? I see we added support for CORS ([here](https://github.com/thinkst/canarytokens/pull/302))

**Comment by i-am-shodan** [comment]
I've tried both

**Comment by jayjb** [comment]
@i-am-shodan, can you check the response header contains the `Access-Control-Allow-Origin: *`? In my test now, it is there. So when you browse to that login page, have the browser dev tools open on the Network tab; you should be able to inspect the request and response.

**Comment by i-am-shodan** [comment]
Worth saying that with Chrome + Edges devtools open the request never appears because preflight fails

**Comment by jayjb** [comment]
Hi @i-am-shodan,

Thanks so much for all the detail. I've been reading up on this and it looks like you are correct. Ill be adding some preflight handling today.

**Comment by jayjb** [comment]
Hi @i-am-shodan,

Please could you give it another shot using a custom web image token? I've added cors preflight support

**Comment by i-am-shodan** [comment]
Success! Thanks for implementing this.

FYI, another thing that is also needed for the scenario is for everything to be under TLS.
