### ISSUE TITLE
[BUG] Microsoft Teams Webhook not functioning

### ISSUE THREAD

**Issue by IHaveAGenericUserName** [thinkst/canarytokens#337]
**Describe the bug**
Trying to add a Microsoft Teams Webhook provides an error message.

Testing webhook with curl works as expected.

**To Reproduce**
1. Attempt to create a new Canarytoken
2. Add webhook url
3. Add descriptive text
4. Click Create my Canarytoken button
5.  Error shown

**Expected behavior**
Teams webhook would be considered valid

**Screenshots**
![image](https://github.com/thinkst/canarytokens/assets/16518889/a2ca890e-e83b-4244-a0f7-0d5cd34ddf22)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Edge]

**Comment by gjcthinkst** [comment]
Hi @IHaveAGenericUserName,

Thanks for raising this! We've implemented support for MS Teams webhooks in #339, so you should now be able to add Teams webhooks.
