### ISSUE TITLE
Windows folder token not working

### ISSUE THREAD

**Issue by Kazakov12** [thinkst/canarytokens#350]
The token does not work when opening a folder. 
Checked via nslookup, the token request is received. But it does not work as a desktop.ini file.
System Win11.

**Comment by DegrangeM** [comment]
Same issue.

**Comment by Kazakov12** [comment]
> Та же проблема.
I have already realized what the problem is, since some Windows system update, a policy has been enabled that forbids the use of this teznika. You have to manually turn it off and then everything will work. I don't remember the exact name

**Comment by jayjb** [comment]
Hi @Kazakov12, @DegrangeM.

As you pointed out, in recent windows updates, there are policies that break the Window ini canarytokens at the moment. We are investigating other methods to do the same thing.

Thanks for raising this.
