### ISSUE TITLE
Windows Folder tokens, username and pc name details

### ISSUE THREAD

**Issue by kuriackovskij** [thinkst/canarytokens#39]
Hi. I am wondering re Windows Folder token. desktop.ini is triggering FQDN which consists of %USERNAME%.%COMPUTERNAME%.%USERDOMAIN%.INI."tokencode"."domainname".
Alerts are working, however I don't see in any reports the username, computer name and domain name which are being passed to CanaryTokens - why those details are passed to canarytokens (for example, why it cannot be used only as "tokencode"."domainname" format?) and can those details be visible in any alerts or history view in canary token?

**Comment by thinkst** [comment]
Hey @kuriackovskij,

Those details dont come through in the email (yet, it can be added with a few more lines of code), but they should come through on the History page under `Basic Details` and then `src_data`. 

If there are not present in the History page, I would try running the following command in powershell:
`$ nslookup.exe PERSON.TESTCOMPUTER.TESTDOMAIN.ini.<token value you created>.<token domain>`

and see if the alert comes through and the extra data comes through on the History page.

Please let me know how it goes.

**Comment by kuriackovskij** [comment]
@thinkst hi,
I tried that step to trigger DNS query from within the powershell, but I only got a Map and **Incident list** on the History page. Here is the screenshot: https://imgur.com/nj7DNsb
And I did that on canarytokens.org. The dns query I did:
`nslookup.exe MEMYSELF.TESTPC.TESTDOMAIN.INI.yz7rrkdf2iqg1uerslik6iheb.canarytokens.com`

**Comment by kuriackovskij** [comment]
@thinkst hi,
Yeah my bad, I initially didn't spot that Incidents are clickable under History page. I can confirm it's working and case can be closed! :-)

**Comment by thinkst** [comment]
@kuriackovskij haha, no stress. Keeping us on our toes here 🤘
