### ISSUE TITLE
CanaryTokens - Fingerprinting Vulnerability (MS WORD)

### ISSUE THREAD

**Issue by benner64** [thinkst/canarytokens#41]
CanaryTokens - Fingerprinting Vulnerability (MS WORD)

MS Word documents are always the same size (15.590-15.670) and after unzipping the docx file, I noticed that the file [word/_rels/footer2.xml.rels] has only a select amount of "random words" in the token URL.

After testing with over 50 samples, I found that using this information could accurately fingerprint which files were infected.

Fix: If you randomize the file size by inserting random string characters into the docx file  and add more words to “pages” and “path_elements” ()like a dictionary dump) and you could fix the problem

Reported by Benjamin Zink Loft

**Comment by thinkst** [comment]
Hey @benner64,

Thanks for reporting this and giving us some ways in which to fix it. 

We have added it to our "things to do" and will let you know as soon as it is done. Alternatively, if you would like to contribute, a PR would be greatly appreciated.
