### ISSUE TITLE
Fix http://canarytokens.org -> https://canarytokens.org in documentation

### ISSUE THREAD

**Issue by JLLeitschuh** [thinkst/canarytokens#47]
You should consider changing header link on this repository to use HTTPS instead of HTTP.

Also, consider changing canarytokens.org so that it automatically redirects to HTTPS.

**Comment by jayjb** [comment]
Hi @JLLeitschuh,

Thanks for the heads up! Ill make that happen. 🤘

**Comment by JLLeitschuh** [comment]
HSTS if possible too!
