### ISSUE TITLE
Injecting Canary URL In Any Word File 

### ISSUE THREAD

**Issue by hassan91** [thinkst/canarytokens#51]
Currently we are using only specific template for word. Is there any mechanism if we can insert URL in any Word File ?

**Comment by jayjb** [comment]
Hi @hassan91,

We do this in our commercial Canarytokens solution. Basically, a potential path is to edit the word document, add an image to it which points to a web Canarytoken. This will force the Word processor to resolve the path and try get an image from the Canarytokens server resulting in an alert.

Please let me know if there is some way I can help you with this.
