### ISSUE TITLE
No Email Recieved

### ISSUE THREAD

**Issue by sohithchowdary** [thinkst/canarytokens#53]
Hello ,
When i'm generating my Canaray token then for example for a pdf or word , if i open this pdf or word i don't get any notification on my Email.
-> used canarytokens.org service
-> operating system windows10

**Comment by jayjb** [comment]
Hi @sohithchowdary,

Thanks for trying our Canarytokens service. Would you mind telling me two things quickly while i investigate?
1. What program did you use to open the pdf?
2. What program did you use to open the word document?

**Comment by chew118** [comment]
having the same problem

using ms word to open a word canary token but didn't receive any email notification

Do we need to whitelist port or url on firewall?
Or the email is blocked by spam filter?

**Comment by jayjb** [comment]
Hi @chew118,

Are you using the canarytokens.org site or are you running your own canarytokens server? 

Please let me know and we can try figure out whats going wrong.

**Comment by sohithchowdary** [comment]
Hey @jayjb 
I used canarytokens.org but its not working man
I didn't received any mail after opening it

**Comment by jayjb** [comment]
Hi @sohithchowdary,

Im sorry its not working for you. Which program did you use to open it? Also which token? I just confirmed that the ms word token and pdf tokens are working for me that the moment. So im sure we will be able to get to the bottom of this

**Comment by The1WhoPrtNocks** [comment]
Also receiving an email or webhook result.
I can however see the request for the webhook leaving my PC.
And i do not apprecaite the comments about my mother :P

**Comment by jayjb** [comment]
Hi @codemonkey2k5,

What OS are you using?

**Comment by codemonkey2k5** [comment]
The token was placed on server 2016 and I tried to access it from both windows 10 and 11.  Windows 10 build 21H1
There is absolutely nothing remarkable about the setup of any of these machines. They all do have the latest windows updates installed.

**Comment by jayjb** [comment]
Hi @codemonkey2k5, @The1WhoPrtNocks, @sohithchowdary,

I've just tested on my Windows 10 machine. The MS Word document works. The PDF document asks for an allow or block permissions. These are both expected. We haven't yet found a way around the PDF security pop up.

I'm closing this issue for now. Please re-open if you test with the current canarytokens.org and have unexpected results or want to continue this discussion.
