### ISSUE TITLE
How to set reply to email using any env

### ISSUE THREAD

**Issue by jaswinder97** [thinkst/canarytokens#54]
For sender env we use: CANARY_ALERT_EMAIL_FROM_ADDRESS

is there any env to declare reply-to email ?

**Comment by jaswinder97** [comment]
@jayjb could you please help me to fix this

**Comment by jayjb** [comment]
Hi @jaswinder97,

We dont currently support this. It should be a quick addition, but we haven't yet got that on our roadmap.

**Comment by jayjb** [comment]
I suspect the way forward here would be to make your `CANARY_ALERT_EMAIL_FROM_ADDRESS=reply-to@example.com`. 

Closing this issue because it isn't something we going to pursue. Thanks for the suggestion.
