### ISSUE TITLE
[BUG] Expired Certificate on the kubeconfig canary host

### ISSUE THREAD

**Issue by sbv-csis** [thinkst/canarytokens#555]
**Describe the bug**
Tried out the kubeconfig canarytoken and got warnings on expired certificate when running a trial run
**To Reproduce**

1. Create a kubeconfig canary on [canarytokens.](https://canarytokens.org/)
2. Click on 'Kubeconfig canarytoken create' and fill in info
3. Use downloaded config with kubectl --kubeconfig kubeconfig api-versions
4. See error:
```
E0730 14:56:18.679564   31585 memcache.go:265] couldn't get current server API group list: Get "https://52.18.63.80:6443/api?timeout=32s": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-07-30T14:56:18+02:00 is after 2024-07-30T12:05:05Z
error: couldn't get available api versions from server: Get "https://52.18.63.80:6443/api?timeout=32s": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-07-30T14:56:18+02:00 is after 2024-07-30T12:05:05Z
```

**Expected behavior**
Expected to get a warning about a loaded kubeconfig for my email

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.13-dispatcher", GitCommit:"eb237aa977a4a0cf4fcec65fc730b4d96af37ccf", GitTreeState:"clean", BuildDate:"2024-02-08T00:21:15Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Unable to connect to the server: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-07-30T14:57:39+02:00 is after 2024-07-30T12:05:05Z
```

**Comment by thinkst-nick** [comment]
Hi @sbv-csis,

Thanks for raising this. We've regenerated the cert and tested that it's working from our side. Could you please confirm your side that re-running the command now successfully triggers an alert?

As a thanks from our side, we'd like to send you a small gift. Please send an email to nick@thinkst.com so that we can make it happen.

Nick
