### ISSUE TITLE
Incident list not expanding

### ISSUE THREAD

**Issue by sfuthings** [thinkst/canarytokens#56]
I have tried Chrome, firefox and Safari and non of them can expand the Incident list nor the Export menu. Tried both docker version and the public web site.

**Comment by jayjb** [comment]
Hi @sfuthings,

Thanks so much for reporting this! Im on it and will ping you back shortly when I've resolved it.

**Comment by jayjb** [comment]
Hi @sfuthings,

Thanks again for reporting this. Please would you mind emailing me at jay [at] thinkst [dot] com. We would like to send you some swag. The issue has been fixed as well. Thanks again!
