### ISSUE TITLE
MS Word + PDF not sending email

### ISSUE THREAD

**Issue by timurozkul** [thinkst/canarytokens#61]
I am using Mac OS Mojave Version 10.14.6.

I downloaded and opened the following MS Word and PDF several times. I have not received any email on my Gmail (I have checked my spam folder). Perhaps I am missing something in the set-up.

**Comment by jayjb** [comment]
Hi @timurozkul,

Can i quickly ask you to send me some details so i can investigate? Please let me know the following:
- what program you opened the PDF with?
- what program you opened the MS word doc with?
- did you download the files from canarytokens.org or are you running your own server?

Thanks for reporting this by the way.

**Comment by timurozkul** [comment]
Yes I used canarytokens.org and I just did the process for the third time just to make sure.
No, I am not running my own server. 

I opened the PDF with apple's default option which is the preview app.
I opened the MS Word with apple's default option which is the Text edit app.

**Comment by jayjb** [comment]
Hi @timurozkul,

Thanks for the information. Currently, the PDF Canarytoken is only triggered if opened with Adobe PDF reader (there are a few others that work, but definitely not all). And it is the same case for the MS Word document. MS Word will trigger the token; but we can't guarantee it across all different word processors. 

Extending these functionality to work across as many word processors and pdf readers is on the road map.
