### ISSUE TITLE
Email not forwarded with SES

### ISSUE THREAD

**Issue by alterEgo123** [thinkst/canarytokens#611]
Hello

I have email receiving set up in SES (Domain in Route53 verified, MX record added, rule set to [contact@mydomain.com](mailto:contact@mydomain.com) active) and then it triggers SNS to forward the email to [me@gmail.com](mailto:me@gmail.com)

When i send email to [contact@mydomain.com](mailto:contact@mydomain.com) using gmail it works and i receive the email in [me@gmail.com](mailto:me@gmail.com)

When I use the email [contact@mydomain.com](mailto:contact@mydomain.com) in CanaryTokens, I don't receive the email even though i see in the interface that the token is triggered

I also tested CanaryTokens with [me@gmail.com](mailto:me@gmail.com) and it works fine

What could be the issue and how to fix this?

**Comment by thinkst-francois** [comment]
Hi @alterEgo123 

For a CanaryTokens Server to be able to send email alerts it needs one of the following sets of settings defined in the `switchboard.env` file:
 - CANARY_MAILGUN_* 
 - CANARY_SENDGRID_*
 - CANARY_SMTP_*
 
 Could you please confirm which one of these you are using on the server.

**Comment by alterEgo123** [comment]
@thinkst-francois I'm using canarytokens.org

**Comment by thinkst-francois** [comment]
@alterEgo123 
Could you please drop us a mail at support [at] canary [dot] tools
and please provide the token and the email you are having an issue with then we can have a look if we see anything in the logs.

**Comment by thinkst-francois** [comment]
Hi @alterEgo123 
I just want to find out if you managed to contact support and if the issue has been resolved.

**Comment by alterEgo123** [comment]
Hello, sorry for the late response. 
I can't disclose which company email I use by contacting your support team, but I contacted AWS team and one of the possible issues is SPF, DKIM or DMARC failures. 
When I analyse one CanaryTokens' email sent to a normal outlook email I see:

````
Authentication-Results: spf=softfail (sender IP is 185.132.181.7)
 smtp.mailfrom=canarytokens.org; dkim=fail (body hash did not verify)
 header.d=canarytokens.org;dmarc=fail action=quarantine
 header.from=canarytokens.org;compauth=none reason=451
 ````

**Comment by thinkst-francois** [comment]
Hello.
Looking at that there is then a chance then that either the AWS SES setup, or some mail filtering / corporate mail server is modifying the message.

Testing a token that for e.g. sends directly to gmail has `dkim-pass` and `spf=pass`
