### ISSUE TITLE
[BUG] NXDOMAINS list in Redis is not cleaned up on startup

### ISSUE THREAD

**Issue by m124523** [thinkst/canarytokens#618]
**Describe the bug**
`CANARY_DOMAINS` and `CANARY_NXDOMAINS` lists are both cached in Redis and cleaned up on startup. However, the latter is not cleaned up.

**To Reproduce**
1. Set `CANARY_NXDOMAINS` to one value, start canarytokens
2. Set `CANARY_NXDOMAINS` to another value, restart canarytokens
3. Generate a PDF token. The old NXDOMAINS is used

**Expected behavior**
The new NXDOMAINS is used

**Desktop (please complete the following information):**
 - OS: Rocky Linux 9
 - Browser: Any

**Additional context**
`remove_canary_domain` is called twice on startup. I believe one of them was meant to be `remove_canary_nxdomain`
https://github.com/thinkst/canarytokens/blob/7847b3e25cacb66721a69ee185e240a7530193fd/frontend/app.py#L340-L345

**Comment by gjcthinkst** [comment]
Hi @m124523 

Thank you for raising this issue. I can confirm that I see the same behaviour. We'll get a fix in and let you know when it has been merged into master.

**Comment by gjcthinkst** [comment]
Hi @m124523 

We've fixed this issue and the change is live on master. Thank you once again for raising the issue.
