### ISSUE TITLE
country information is not available on token manage page

### ISSUE THREAD

**Issue by jaswinder97** [thinkst/canarytokens#63]
![canarytoken-trigger-info-page](https://user-images.githubusercontent.com/17950241/83888840-0032fb80-a768-11ea-8a6a-e329295460d2.png)

**Comment by jayjb** [comment]
hi @jaswinder97,

In order to get the country information, you will need to add an ipinfo api key to the `.env` file. We mention it on `canarytokens-docker` repo:

> we have added an extra switchboard.env called CANARY_IPINFO_API_KEY. This allows you to use your ipinfo.io api key if you want to (keep in mind ipinfo.io does have a free tier of up to 1000 requests a day).

**Comment by jaswinder97** [comment]
thanks @jayjb 
I will try it today

**Comment by jaswinder97** [comment]
@jayjb it seems like broken on latest commit and requires GOOGLE API KEY

![Screenshot - 2021-06-26T230901 287](https://user-images.githubusercontent.com/17950241/123521331-9e776380-d6d3-11eb-8c95-d7db4eb55389.png)

![Uploading Screenshot - 2021-06-26T230929.538.png…]()

**Comment by jaswinder97** [comment]
@jayjb it seems not working for me even after adding the key to .env

**Comment by jayjb** [comment]
Hi @jaswinder97,

Sorry for delay. Can you confirm:
1. you are running the latest canarytokens code?
2. you have `CANARY_IPINFO_API_KEY` in your `switchboard.env`?
3. you have `CANARY_GOOGLE_API_KEY` in your `frontend.env`?

**Comment by jaswinder97** [comment]
@jayjb we are using old frontend but with latest backend, I think that is causing an issue; we can close it

**Comment by jayjb** [comment]
Thanks for confirming @jaswinder97
