### ISSUE TITLE
Question: List active / created tokens

### ISSUE THREAD

**Issue by silascutler** [thinkst/canarytokens#70]
Simple question / sorry I didn't find an answer in the documentation  - Is there a way to list all of the active / created tokens?

**Comment by jayjb** [comment]
Hi @silascutler,

No stress at all. There isn't a way to list all active tokens however if you are running your own Canarytokens servers, you can follow these steps to list them:
1. ssh into host that is running your Canarytokens docker.
2. `sudo docker exec -ti redis redis-cli` #here we are dropping into a redis shell on the redis container of your Canarytokens docker
3. `keys canarydrop:*` # this will list all your hash Canarytoken objects.

I hope this helps.

**Comment by jayjb** [comment]
Closing issue. I've made a note of the steps used in our new FAQ over [here](https://github.com/thinkst/canarytokens/wiki#how-can-i-list-all-created-canarytokens-on-my-private-canarytokens-server)
