### ISSUE TITLE
Provide a customisable hole off timer for repeat alerts

### ISSUE THREAD

**Issue by SimonGurney** [thinkst/canarytokens#72]
The User class throttles alerts to 1 alert per 60 second window, which drops to 1 alert per 5 second window when running in "DEBUG".

This may not be the desired behaviour, particularly with webhook alerts configured.  Can this be made configurable via ENV vars like other settings.  I was thinking a tuneable window length and alert cap per window or to fully disable the feature.

Happy to submit a merge request if needed.

**Comment by jayjb** [comment]
Hi @SimonGurney,

We haven't had many requests for this (or none that I can recall). If you happy to take a crack at it, i'd be more than happy to help out and send you something as a thanks for contributing too!

**Comment by SimonGurney** [comment]
Hi @jayjb 

That would be awesome.  Shall I do a pull request?  I'm not overly familiar with GitHub etiquette :)

**Comment by jayjb** [comment]
Hi @SimonGurney,

Haha, yessir. A PR would be great thanks! Hmmm, now that you mention GitHub etiquette i'm unsure whether i've followed it too 🙈  🤣
