### ISSUE TITLE
canarytokens.com does not resolve from DigitalOcean droplets

### ISSUE THREAD

**Issue by ajxchapman** [thinkst/canarytokens#74]
```sh
droplet:~# nslookup canarytokens.com
Server:         127.0.0.53
Address:        127.0.0.53#53

** server can't find canarytokens.com: SERVFAIL
```

This appears to be due to Digital Ocean resolvers expecting the 'Authority' flag to be set on responses from a SOA for a domain.

**Comment by jayjb** [comment]
Thanks so much for finding and fixing this @ajxchapman! Look forward to hearing from you
