### ISSUE TITLE
How to setup lambda function for CANARY_AWSID_URL

### ISSUE THREAD

**Issue by manipulator01** [thinkst/canarytokens#76]
Hello,

**I would like to use my own AWS account to generate AWS tokens** but I cannot find any documentation on how to setup required lambda functions AWS.

I noticed that [documentation](https://github.com/thinkst/canarytokens/blob/master/README.md) mentions following information:

>.... we have added the ability to specify your own AWSID lambda so that you may host your own. The setting is placed in frontend.env under CANARY_AWSID_URL. If this value is not specified, it will use our default hosted lambda.

But I cannot see how I can generate `CANARY_AWSID_URL` and do required setup on my AWS account.

Please advise

**Comment by jayjb** [comment]
Hi @manipulator01,

Sorry for the delayed response. Currently, we haven't shared how that whole AWS ID token works regarding actual source code etc. We have just parameterised it in case you figure your own way to create an AWS ID Canarytoken.

**Comment by jayjb** [comment]
Closing this issue because we haven't released how to create your own AWS ID infrastructure yet. However you may take a look at [SpaceSiren](https://github.com/spacesiren/spacesiren) or the original work [SpaceCrab](https://bitbucket.org/asecurityteam/spacecrab/src/master/).
