### ISSUE TITLE
What is https://check.torproject.org/exit-addresses ?

### ISSUE THREAD

**Issue by frostmx** [thinkst/canarytokens#80]
I have looked through logs and noticed some strange thing:

2021-01-29T07:29:03+0000 [twisted.web.client.HTTPClientFactory#info] Starting factory <HTTPClientFactory: https://check.torproject.org/exit-addresses>
2021-01-29T07:29:04+0000 [twisted.web.client.HTTPClientFactory#info] Stopping factory <HTTPClientFactory: https://check.torproject.org/exit-addresses>

What does it need for?
And can I turn it off?

**Comment by frostmx** [comment]
So I want to install app inside without internet connection at all.
But if it cannot connect to ipinfo.io (but i dont use any api key) it hangs at all.

**Comment by frostmx** [comment]
Ok. I ve done some research and found what it is.
But there is still trouble without internet access.

**Comment by jayjb** [comment]
Hi @frostmx,

Sorry for the delayed response. Is your Canarytokens server running purely on an internal network? I.e. why no internet access? The reason i ask is that if a token is triggered outside your network, then it wont make its way back to your server and send an alert.

**Comment by jayjb** [comment]
Closing this issue as inactive. Please re-open if you have more to discuss.
