### ISSUE TITLE
Customize mailgun API endpoint

### ISSUE THREAD

**Issue by JC5** [thinkst/canarytokens#92]
https://github.com/thinkst/canarytokens/blob/13fad642b11159715c274dea9c1fae85fa47f116/channel_output_email.py#L119

I am in the EU. I can't use mailgun because it's hardcoded to the US endpoints.

This is documented here: https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-via-api

**Comment by jayjb** [comment]
Hi @JC5,

Thats very useful. Thank you. Ill try get a fix in to get it sorted for you.

**Comment by jayjb** [comment]
tracking it [here](https://github.com/thinkst/canarytokens/pull/98)

**Comment by JC5** [comment]
🥳
